`# PostgreSQL — dvdrental DB холболт       
spring.datasource.url=jdbc:postgresql://localhost:5432/actor_api                                                 
spring.datasource.username=postgres                       
spring.datasource.password=postgres                                                                              
# spring.datasource.driver-class-name=org.postgresql.Driver 
                                                                                                                
# JSON field нэрийг snake_case болгох (firstName → first_name)                                                   
spring.jackson.property-naming-strategy=SNAKE_CASE
                                                                                                                
# Server port                                             
server.port=8080`